### ISSUE TITLE
Hilt with lsParanoid

### ISSUE THREAD

**Issue by BreadInjection** [LSPosed/LSParanoid#18]
An Exception is thrown after building a project that uses Hilt. It only works when the project doesn't have any caches.

Exception:
Caused by: org.gradle.api.UncheckedIOException: java.util.zip.ZipException: duplicate entry: dagger/hilt/internal/aggregatedroot/codegen/_com_example_lsparanoidtest_App.class
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:62)
	at org.gradle.internal.UncheckedExceptio
n.throwAsUncheckedException(UncheckedException.java:41)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:128)

Here is a demo project : [lsparanoidDemo.zip](https://github.com/LSPosed/LSParanoid/files/11685388/lsparanoidDemo.zip)
Do you have any Solution for this Issue?

**Comment by edyknd** [comment]
@BreadInjection  I have the same problem.
did you solve it?

**Comment by saleho27** [comment]
In my case I have to use gradle 8.5 (error if gradle 8.4)

`distributionUrl=https\://services.gradle.org/distributions/gradle-8.5-bin.zip`
